# Generated by Django 3.0.4 on 2020-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='m_DataRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(choices=[('Юридическое лицо', 'Юридическое лицо'), ('Индивидуальный предприниматель', 'Индивидуальный предприниматель'), ('Самозанятый', 'Самозанятый')], max_length=40)),
                ('inn', models.IntegerField()),
                ('all_name', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='m_Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=120)),
                ('namder', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
